version: "3.1"

# mount the dbt directory as a volume
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "127.0.0.1:27017:27017"            # LocalStack Gateway
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - "./mongovol:/data/db"

  localstack:
      container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
      image: localstack/localstack
      ports:
        - "127.0.0.1:4566:4566"            # LocalStack Gateway
        - "127.0.0.1:4510-4559:4510-4559"  # external services port range
        - "127.0.0.1:8081:8081"            # Web UI
  #    extra_hosts:
  #      - "host.docker.internal:host-gateway"
      environment:
        - DEBUG=1
        # - DOCKER_HOST=unix:///var/run/docker.sock
        # - PORT_WEB_UI=8080
        # - AWS_ACCESS_KEY_ID=access-key-id
        # - AWS_SECRET_ACCESS_KEY=secret-access-key
        # - LAMBDA_DOCKER_NETWORK=host
        # - LAMBDA_EXECUTOR=docker
      volumes:
        - "./myvolume:/var/lib/localstack"
        - "/var/run/docker.sock:/var/run/docker.sock"
  scheduler:
    volumes:
      - ./aws:/home/astro/.aws